apiVersion: v1
kind: Service
metadata:
  name: userapp-service
  namespace: rspace-userapp
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: TCP
      port: 9191
      targetPort: 9191
  type: NodePort
  