apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-svc-deployment
  namespace: rspace-userapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: spring-boot-k8s
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: user-app-container
          image: 'praneethrsp/user-service:1.0.0-1'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9191
      restartPolicy: Always
      
